[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
loglevel=info

[program:api-gateway]
command=java %(ENV_JAVA_OPTS)s -jar /app/services/ApiGateway-1.0.jar
directory=/app
autostart=true
autorestart=true
startretries=5
startsecs=60
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=100

[program:user-service]
command=java %(ENV_JAVA_OPTS)s -jar /app/services/UserService-1.0.jar
directory=/app
autostart=true
autorestart=true
startretries=5
startsecs=60
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=200
environment=DB_HOST="%(ENV_DB_HOST)s",DB_PORT="%(ENV_DB_PORT)s",DB_NAME="%(ENV_DB_NAME)s",DB_USER="%(ENV_DB_USER)s",DB_PASSWORD="%(ENV_DB_PASSWORD)s"

[program:recharge-service]
command=java %(ENV_JAVA_OPTS)s -jar /app/services/RechargeService-1.0.jar
directory=/app
autostart=true
autorestart=true
startretries=5
startsecs=60
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=200
environment=DB_HOST="%(ENV_DB_HOST)s",DB_PORT="%(ENV_DB_PORT)s",DB_NAME="%(ENV_DB_NAME)s",DB_USER="%(ENV_DB_USER)s",DB_PASSWORD="%(ENV_DB_PASSWORD)s"

[program:payment-service]
command=java %(ENV_JAVA_OPTS)s -jar /app/services/PaymentService-1.0.jar
directory=/app
autostart=true
autorestart=true
startretries=5
startsecs=60
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=200
environment=DB_HOST="%(ENV_DB_HOST)s",DB_PORT="%(ENV_DB_PORT)s",DB_NAME="%(ENV_DB_NAME)s",DB_USER="%(ENV_DB_USER)s",DB_PASSWORD="%(ENV_DB_PASSWORD)s"

[program:notification-service]
command=java %(ENV_JAVA_OPTS)s -jar /app/services/NotificationService-1.0.jar
directory=/app
autostart=true
autorestart=true
startretries=5
startsecs=60
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=200
environment=DB_HOST="%(ENV_DB_HOST)s",DB_PORT="%(ENV_DB_PORT)s",DB_NAME="%(ENV_DB_NAME)s",DB_USER="%(ENV_DB_USER)s",DB_PASSWORD="%(ENV_DB_PASSWORD)s"

[program:operator-service]
command=java %(ENV_JAVA_OPTS)s -jar /app/services/OperatorService-1.0.jar
directory=/app
autostart=true
autorestart=true
startretries=5
startsecs=60
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=200
environment=DB_HOST="%(ENV_DB_HOST)s",DB_PORT="%(ENV_DB_PORT)s",DB_NAME="%(ENV_DB_NAME)s",DB_USER="%(ENV_DB_USER)s",DB_PASSWORD="%(ENV_DB_PASSWORD)s"

[unix_http_server]
file=/app/supervisor/supervisor.sock

[supervisorctl]
serverurl=unix:///app/supervisor/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
