spring:
  application:
    name: user-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: Amanking2425@gmail.com
    password: baoxxzjzuozqogxj   
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

---
spring:
  config:
    activate:
      on-profile: default
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:postgresql://localhost:5432/omincharge
    username: aman
    password: tiger
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: docker
    import: optional:configserver:http://config-server:8888

  datasource:
    url: jdbc:postgresql://postgres:5432/omincharge
    username: aman
    password: tiger
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/