spring:
  application:
    name: notification-service

server:
  port: 8085

rabbitmq:
  exchange:
    recharge: recharge.exchange
    payment: payment.exchange
  queue:
    recharge-notification: recharge.notification.queue
    payment-notification: payment.notification.queue
  routing-key:
    recharge: recharge.notification
    payment: payment.notification

eureka:
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
---
spring:
  config:
    activate:
      on-profile: default
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: docker
    import: optional:configserver:http://config-server:8888
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/